apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-chaos
spec:
  selector:
    labelSelectors:
      app: nginx
  mode: all
  action: delay
  delay:
    latency: "100ms"
    jitter: "10ms"
    correlation: "50"
  loss:
    loss: "10"
    correlation: "25"
  duration: "300s"