apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113