apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-failure-schedule
spec:
  schedule: "@every 10m"
  type: PodChaos  # Explicitly specify the type
  podChaos:
    selector:
      labelSelectors:
        app: nginx
    mode: one
    action: pod-kill
    duration: "300s"